### PR TITLE
feat: add pss compliance

### PR DESCRIPTION
**Pull request by itaysk**
related: https://github.com/aquasecurity/trivy/issues/3342
(need to add docs in separate PR)

### CODE REVIEW

**Comment by chen-keinan** [comment]
@itaysk it will be great to add a [test to protect it](https://github.com/aquasecurity/defsec/blob/master/internal/specs/loader_test.go)

**Comment by itaysk** [comment]
added. BTW - I'm not sure what the spec.id used for? seems like all the report ignore it

**Review by chen-keinan — DISMISSED** [review]

**Comment by itaysk** [comment]
converted to draft until #1120 is merged

**Comment by itaysk** [comment]
rebased with latest changes

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
