### PR TITLE
feat: add support for IAM identity center permission set session duration

### PR DESCRIPTION
**Pull request by gantta**
Related to https://github.com/aquasecurity/trivy/discussions/5877

Adds new AWS service for IAM Identity Center Permission Set to address [NIST CPRT SP 800-53 Release 5.1.1 AC-12](https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_53_5_1_1/home?element=AC-12)

### CODE REVIEW

**Comment by simar7** [comment]
could you resolve the merge conflict?

**Comment by gantta** [comment]
merge conflict resolved. The Meta struct is not present in my branch in the `/pkg/providers/aws/aws.go` file so please confirm it should remain.

**Comment by simar7** [comment]
> merge conflict resolved. The Meta struct is not present in my branch in the `/pkg/providers/aws/aws.go` file so please confirm it should remain.

You have to rebase on latest master branch.

**Comment by gantta** [comment]
rebase complete. Should be good for review now.

**Comment by simar7** [comment]
> rebase complete. Should be good for review now.

tests are still red. Could you look into it? Might have to run `go mod tidy` and commit changes, if any.

**Comment by gantta** [comment]
`go mod tidy` is giving the following errors:
```
github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws/iamidentitycenter imports
        github.com/aquasecurity/defsec/pkg/scanners/cloudformation/parser: no matching versions for query "latest"
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iamidentitycenter tested by
        github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iamidentitycenter.test imports
        github.com/aquasecurity/defsec/internal/adapters/terraform/tftestutil: no matching versions for query "latest"
```
Not sure what I can do with this at this point.

**Comment by simar7** [comment]
> `go mod tidy` is giving the following errors:
> 
> ```
> github.com/aquasecurity/defsec/internal/adapters/cloudformation/aws/iamidentitycenter imports
>         github.com/aquasecurity/defsec/pkg/scanners/cloudformation/parser: no matching versions for query "latest"
> github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iamidentitycenter tested by
>         github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iamidentitycenter.test imports
>         github.com/aquasecurity/defsec/internal/adapters/terraform/tftestutil: no matching versions for query "latest"
> ```
> 
> Not sure what I can do with this at this point.

Sorry about that. We're in the middle of a project restructure and you caught us. Eventually the policies should live in the new repo https://github.com/aquasecurity/trivy-policies and any adapters in this repo https://github.com/aquasecurity/trivy-iac

I'll get to your PR shortly, I might have to recreate it for you but that's fine as I realize it's probably easier for me to do so and would also help us to document how someone can contribute externally. Appreciate the patience.

**Comment by gantta** [comment]
@simar7 Curious if there is any ETA that can be provided on when the new PR can go in?

**Comment by simar7** [comment]
> @simar7 Curious if there is any ETA that can be provided on when the new PR can go in?

We need these two changes merged before we can merge this PR.

1. https://github.com/aquasecurity/trivy/pull/6005
2. https://github.com/aquasecurity/trivy/pull/6006

At the moment, I don't have an ETA for you but we'll get to it when the above are merged.

**Comment by gantta** [comment]
@simar7 any updates you can provide on ETA for when we can get this PR completed?

**Comment by simar7** [comment]
> @simar7 any updates you can provide on ETA for when we can get this PR completed?

@gantta defsec and other iac ancillary repos have been merged into trivy. If you could open a PR against the trivy repo we can help you merge it. Thanks for the understanding.

**Pull request closed without merging**
