### PR TITLE
feat: Add terraform scanner (ported from tfsec)

### PR DESCRIPTION
**Pull request by liamg**

### CODE REVIEW

**Comment by owenrumney** [comment]
Wot, no tests?

**Review by owenrumney — DISMISSED** [review]

**Comment by liamg** [comment]
> Wot, no tests?

Added lots of tests now :+1:

**Review by owenrumney — APPROVED** [review]

**Comment by owenrumney** [comment]
> > Wot, no tests?
> 
> Added lots of tests now +1

too many tests, its like you don't have confidence in the code

**Comment by liamg** [comment]
```
find . -type f -name "*_test.go" -print0 | head -z -n 10 | xargs -0 rm
```

**Pull request merged**
