### PR TITLE
fix(aws): use correct signing region

### PR DESCRIPTION
**Pull request by nikpivkin**
See https://github.com/aquasecurity/trivy/issues/4883

### CODE REVIEW

**Comment by nikpivkin** [comment]
@simar7 `Test_FileScanExampleWithResultFunction` test fail only on Windwos. Is the test fluky?

**Comment by simar7** [comment]
> @simar7 `Test_FileScanExampleWithResultFunction` test fail only on Windwos. Is the test fluky?

Hmm not sure. Are you about to spin up a Windows VM to try it out?

I can try to spin one up as well to see what's going on.

**Comment by nikpivkin** [comment]
@simar7 I have a windows pc, I'll try

**Comment by nikpivkin** [comment]
@simar7 The same test [fell](https://github.com/aquasecurity/defsec/actions/runs/5745830395/job/15574388370?pr=1413) in another PR

**Comment by nikpivkin** [comment]
@simar7 I'm waiting for [this](https://github.com/aquasecurity/defsec/pull/1415) PR to be merged

**Comment by simar7** [comment]
> @simar7 I'm waiting for [this](https://github.com/aquasecurity/defsec/pull/1415) PR to be merged 

Merged

**Comment by nikpivkin** [comment]
@simar7 Can you restart tests?

**Comment by knqyf263** [comment]
@simar7 You enabled auto-merge, but you didn't approve it. Is it a mistake or intended?

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
> @simar7 You enabled auto-merge, but you didn't approve it. Is it a mistake or intended? I'd include this fix in [v0.44.1](https://github.com/aquasecurity/trivy/milestone/24).

Not entirely sure what happened there. I had approved the changes but my approval seems to be missing from GitHub. I've reapproved again. Once it goes through, I will cut a new defsec patch release.

**Pull request merged**
