### PR TITLE
feat: add gcp bucket customer-managed key check

### LINKED ISSUE #914: check: GCP storage bucket customer-managed encryption key
**Provider**
GCP

**Severity**
LOW

**Short Code**
bucket-encryption-customer-key

**Description**
Ensure that GCP storage buckets are configured to use customer-managed encryption keys.

**Link**
https://cloud.google.com/storage/docs/encryption/customer-managed-keys

### PR DESCRIPTION
**Pull request by ryan-jan**
As discussed with @liamg in the tfsec repo this PR is for issue #914 

Resolves #914

### CODE REVIEW

**Review by liamg — DISMISSED** [review]
LGTM, thank you! :rocket: 

If you could sign the CLA (see the bot message above) we can get this merged.

**Comment by ryan-jan** [comment]
> LGTM, thank you! 🚀
> 
> If you could sign the CLA (see the bot message above) we can get this merged.

I did, but for some reason it is not showing and now when I click on the link again it shows as me having already signed it?? Strange...

**Comment by liamg** [comment]
Hey @ryan-jan - I think you need to run `make docs` to generate the documentation from your rule.

**Comment by ryan-jan** [comment]
> Hey @ryan-jan - I think you need to run `make docs` to generate the documentation from your rule.

@liamg no worries, I've added the doc now.

FYI I was following the [tfsec CONTRIBUTING.md](https://github.com/aquasecurity/tfsec/blob/master/CONTRIBUTING.md) and as far as I can see there is no mention of running `make docs`. Would you like me to raise a PR to update the CONTRIBUTING.md?

**Review by liamg — APPROVED** [review]
:+1:

**Pull request merged**
