### PR TITLE
feat(spec): add support for CIS Docker Community Edition Benchmark

### PR DESCRIPTION
**Pull request by knqyf263**
# Description
This PR adds support for CIS Docker Community Edition Benchmark.
https://www.cisecurity.org/benchmark/docker

# Blockers
- https://github.com/aquasecurity/defsec/pull/1141
- https://github.com/aquasecurity/defsec/pull/1139

### CODE REVIEW

**Comment by knqyf263** [comment]
All relevant PRs were merged. It is ready for review! @simar7 @giorod3 @chen-keinan

**Comment by chen-keinan** [comment]
@knqyf263 could you please add it to [tests](https://github.com/aquasecurity/defsec/blob/master/internal/specs/loader_test.go) , just to make sure yaml is not broken

**Comment by knqyf263** [comment]
Added in https://github.com/aquasecurity/defsec/pull/1144/commits/2a69430511efebb28e4b4fd2a48d579ef2ff4bd3

**Review by chen-keinan — APPROVED** [review]

**Review by simar7 — APPROVED** [review]
I think the CLA check is broken again but it lgtm 🚢 :shipit:

**Pull request merged**
